/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { initializeApp, getApps, FirebaseApp } from 'firebase/app';
import {
  getAuth,
  signInWithCustomToken,
  signOut as firebaseSignOut,
  Auth,
} from 'firebase/auth';
import { 
  getFirestore, 
  collection, 
  doc, 
  setDoc, 
  deleteDoc,
  onSnapshot, 
  writeBatch,
  Firestore,
  Unsubscribe
} from 'firebase/firestore';
import { Student, Teacher, SchoolSettings } from '../types';

let app: FirebaseApp | null = null;
let db: Firestore | null = null;
let authInstance: Auth | null = null;
let isFirebaseInitialized = false;

// Attempt to load Firebase configuration dynamically from /firebase-applet-config.json
// or fallback to predefined environment variables
export async function initFirebaseService(onReady: (active: boolean) => void) {
  try {
    // Check environment variables first
    const metaEnv = (import.meta as any).env || {};
    const envConfig = {
      apiKey: metaEnv.VITE_FIREBASE_API_KEY,
      authDomain: metaEnv.VITE_FIREBASE_AUTH_DOMAIN,
      projectId: metaEnv.VITE_FIREBASE_PROJECT_ID,
      storageBucket: metaEnv.VITE_FIREBASE_STORAGE_BUCKET,
      messagingSenderId: metaEnv.VITE_FIREBASE_MESSAGING_SENDER_ID,
      appId: metaEnv.VITE_FIREBASE_APP_ID,
    };

    let finalConfig: any = null;

    if (envConfig.apiKey && envConfig.projectId) {
      finalConfig = envConfig;
    } else {
      // Try to fetch public/firebase-applet-config.json which is generated by the AI Studio platform
      const response = await fetch('/firebase-applet-config.json');
      if (response.ok) {
        finalConfig = await response.json();
      }
    }

    if (finalConfig && finalConfig.apiKey && finalConfig.projectId) {
      if (getApps().length === 0) {
        app = initializeApp(finalConfig);
      } else {
        app = getApps()[0];
      }

      authInstance = getAuth(app);
      
      // Use custom firestore database ID if specified in configuration
      if (finalConfig.firestoreDatabaseId) {
        db = getFirestore(app, finalConfig.firestoreDatabaseId);
      } else {
        db = getFirestore(app);
      }
      
      isFirebaseInitialized = true;
      console.log('Firebase synced and initialized successfully on port 3000');
      onReady(true);
      return true;
    }
  } catch (error) {
    console.warn('Firebase setup is pending or in Local Fallback mode:', error);
  }
  
  isFirebaseInitialized = false;
  onReady(false);
  return false;
}

export function isFirebaseReady(): boolean {
  return isFirebaseInitialized && db !== null;
}

/**
 * Sign in to Firebase Auth using the custom token minted by our backend
 * after it verified the person's PIN server-side. This is what makes
 * request.auth.token.schoolId / .role available to Firestore Security
 * Rules for every subsequent read/write.
 */
export async function signInWithBackendToken(customToken: string): Promise<boolean> {
  if (!authInstance) return false;
  try {
    await signInWithCustomToken(authInstance, customToken);
    return true;
  } catch (error) {
    console.error('Error signing in with custom token:', error);
    return false;
  }
}

export async function signOutFirebase(): Promise<void> {
  if (!authInstance) return;
  try {
    await firebaseSignOut(authInstance);
  } catch (error) {
    console.warn('Error signing out of Firebase Auth:', error);
  }
}

/**
 * Fresh Firebase ID token for the signed-in user, to send as
 * `Authorization: Bearer <token>` on calls to our backend API. Returns null
 * if nobody is signed in (e.g. running fully offline/local mode).
 */
export async function getFirebaseIdToken(): Promise<string | null> {
  if (!authInstance || !authInstance.currentUser) return null;
  try {
    return await authInstance.currentUser.getIdToken();
  } catch (error) {
    console.warn('Error getting Firebase ID token:', error);
    return null;
  }
}

export enum OperationType {
  CREATE = 'create',
  UPDATE = 'update',
  DELETE = 'delete',
  LIST = 'list',
  GET = 'get',
  WRITE = 'write',
}

interface FirestoreErrorInfo {
  error: string;
  operationType: OperationType;
  path: string | null;
  authInfo: {
    userId: string | null;
  };
}

function handleFirestoreError(error: unknown, operationType: OperationType, path: string | null) {
  const errInfo: FirestoreErrorInfo = {
    error: error instanceof Error ? error.message : String(error),
    authInfo: {
      userId: 'anonymous'
    },
    operationType,
    path
  };
  console.error('Firestore Error: ', JSON.stringify(errInfo));
  throw new Error(JSON.stringify(errInfo));
}

/**
 * Sync School Settings document in real-time
 */
export function subscribeToSchoolSettings(schoolId: string, onUpdate: (settings: SchoolSettings) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(doc(db, 'schools', schoolId, 'settings', 'school'), (snapshot) => {
    if (snapshot.exists()) {
      onUpdate(snapshot.data() as SchoolSettings);
    }
  }, (error) => {
    handleFirestoreError(error, OperationType.GET, `schools/${schoolId}/settings/school`);
  });
}

/**
 * Save School Settings
 */
export async function dbSaveSchoolSettings(schoolId: string, settings: SchoolSettings) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'settings', 'school'), settings);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/settings/school`);
    return false;
  }
}

/**
 * Sync Students collection in real-time
 */
export function subscribeToStudents(schoolId: string, onUpdate: (students: Student[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'schools', schoolId, 'students'), (snapshot) => {
    const list: Student[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Student);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, `schools/${schoolId}/students`);
  });
}

/**
 * Sync Teachers collection in real-time
 */
export function subscribeToTeachers(schoolId: string, onUpdate: (teachers: Teacher[]) => void): Unsubscribe | null {
  if (!db) return null;
  return onSnapshot(collection(db, 'schools', schoolId, 'teachers'), (snapshot) => {
    const list: Teacher[] = [];
    snapshot.forEach((doc) => {
      list.push(doc.data() as Teacher);
    });
    onUpdate(list);
  }, (error) => {
    handleFirestoreError(error, OperationType.LIST, `schools/${schoolId}/teachers`);
  });
}

/**
 * CRUD functions for Students
 */
export async function dbSaveStudent(schoolId: string, student: Student) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'students', student.id), student);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/students/${student.id}`);
    return false;
  }
}

export async function dbDeleteStudent(schoolId: string, id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'schools', schoolId, 'students', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `schools/${schoolId}/students/${id}`);
    return false;
  }
}

/**
 * CRUD functions for Teachers
 */
export async function dbSaveTeacher(schoolId: string, teacher: Teacher) {
  if (!db) return false;
  try {
    await setDoc(doc(db, 'schools', schoolId, 'teachers', teacher.id), teacher);
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/teachers/${teacher.id}`);
    return false;
  }
}

export async function dbDeleteTeacher(schoolId: string, id: string) {
  if (!db) return false;
  try {
    await deleteDoc(doc(db, 'schools', schoolId, 'teachers', id));
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.DELETE, `schools/${schoolId}/teachers/${id}`);
    return false;
  }
}

/**
 * One-time data uploading (Migration from localStorage to Cloud Firestore).
 * NOTE: PINs are intentionally NOT migrated here — they must never be
 * written to Firestore directly from the client (see firestore.rules).
 * Staff PINs created while offline should be re-created via the Security
 * Settings screen once the school is connected to the cloud, which goes
 * through the backend's hashing endpoint instead.
 */
export async function uploadLocalDataToFirebase(schoolId: string, students: Student[], teachers: Teacher[]) {
  if (!db) return false;
  try {
    const batch = writeBatch(db);
    
    // Migrate students
    for (const s of students) {
      const docRef = doc(db, 'schools', schoolId, 'students', s.id);
      batch.set(docRef, s);
    }
    
    // Migrate teachers
    for (const t of teachers) {
      const docRef = doc(db, 'schools', schoolId, 'teachers', t.id);
      batch.set(docRef, t);
    }

    await batch.commit();
    return true;
  } catch (error) {
    handleFirestoreError(error, OperationType.WRITE, `schools/${schoolId}/batch-migration`);
    return false;
  }
}
